Cypress.Commands.add('login', (usuario, senha) => {
    cy.get('#username')
        .type(usuario)
    cy.get('#password')
        .type(`${senha}}{enter}`)
})

Cypress.Commands.add('preCadastro', (usuario, senha, nome, sobrenome) => {
    cy.get('#reg_email')
        .type(usuario)
    cy.get('#reg_password')
        .type(`${senha}{enter}`)
    cy.get('.woocommerce-MyAccount-navigation-link--edit-account > a')
        .click()
    cy.get('#account_first_name')
        .type(nome)
    cy.get('#account_last_name')
        .type(sobrenome)
    cy.get('.woocommerce-Button')
        .click()
})

Cypress.Commands.add('adicionaProduto', (produto, tamanho, cor, quantidade) => {
    cy.get('[class = "product-block grid"]')
        .contains(produto)
        .click()
    cy.get('.button-variable-item-' + tamanho)
        .click()
    cy.get('.button-variable-item-' + cor)
        .click()
    cy.get('.input-text')
        .clear()
        .type(quantidade)
    cy.get('.single_add_to_cart_button')
        .click()
})